### ISSUE TITLE
Inline return

### ISSUE THREAD

**Issue by t-poeschl** [FAAREN-tech/laravel-custom-uuids#2]
https://github.com/FAAREN-tech/laravel-custom-uuids/blob/5abe47170482449bc20053bc2eac0353dfed2882/src/Helpers/UuidHelper.php#L64

Maybe inline return and save 1 line of code:
return (DB::table($table)->where('uuid', $uuid)->count() === 0);

**Comment by Brotzka** [comment]
Merged pull request. 

Thank you!
